scalar DateTime

type Author {
  id: Int!
  displayName: String!
  picture: String!
  posts: [Post!]
  createAt: DateTime!
  comments: [Comment!]
}

type Post {
  id: Int!
  author: Author!
  title: String!
  content: String
  comments: [Comment!]
  createAt: DateTime!
  publishedAt: DateTime
}

type Comment {
  id: Int!
  post: Post!
  username: String!
  text: String!
  replyTo: Comment
}

type Query {
  author(id: Int!): Author
  post(id: Int!): Post
  postComments(postId: Int!): [Comment!]
  allPosts: [Post!]
}

input CreatePostInput {
  authorId: Int!
  title: String!
  content: String
}

input CreateCommentInput {
  postId: Int!
  username: String!
  text: String!
  replyToId: Int
}

type Mutation {
  createPost(input: CreatePostInput): Post
  publishPost(id: Int!): Post
  createComment(id: Int!, input: CreateCommentInput): Comment
}
